Feature/user field change listener
mBeym/ILIAS pull request #2
Opened 2021-09-24 09:01 UTC by mBeym

2021-10-25 09:23 UTC, mjansenDatabay requested changes

2021-10-25 09:23 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilMailAppEventListener.php
> +        if ($a_component === "Services/User" && $a_event === "onUserFieldAttributesChanged") {
Could we try to move the code to an instance method and initialize the `$DIC` in the constructor, similar to the `ilTermsOfServiceAppEventListener`?

2021-10-25 09:23 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilMailAppEventListener.php
> +                $result = $db->query("SELECT value FROM settings WHERE module = 'common' AND keyword = 'mail_address_option'");
Please don't query the database here, please use `$DIC->settings()->get('mail_address_option')`.

2021-10-25 09:23 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilMailUserFieldChangeListener.php
> +    public function __construct(Container $dic)
Could you try to only pass the necessary dependencies instead of the complete `Container`?

2021-10-25 09:23 UTC, mjansenDatabay commented on Services/User/classes/class.ilObjUserFolderGUI.php
> +    public function showFieldChangeComponentsListeningConfirmDialog(array $interestedChangeListeners) : void
Could you try to use a PHPDoc comment to describe the `array`?

2021-10-25 09:23 UTC, mjansenDatabay commented on Services/User/classes/class.ilObjUserFolderGUI.php
> +    public function handleChangeListeners(array $changedFields, array $fieldProperties) : bool
Could you try to use a PHPDoc comment to describe the `array` parameters?

2021-10-25 09:23 UTC, mjansenDatabay commented on Services/User/classes/class.ilObjUserFolderGUI.php
> +    private function collectChangedFields() : array
Could you try to use a PHPDoc comment to describe the `array` return value?

2021-10-25 09:23 UTC, mjansenDatabay commented on Services/User/templates/default/tpl.usr_field_change_listener_confirm.html
> +<ul>
Do we really need this? Can't we achieve the same with nesting `$DIC->ui()->listing()->...` elements?'

2021-10-25 10:36 UTC, mBeym commented on Services/Mail/classes/class.ilMailUserFieldChangeListener.php
> +    public function __construct(Container $dic)
How would I know what things the person creating the listener need?

I could remove passing the Container in general, but then every listener would need to get it themself using
```php
global $DIC;
```

2021-10-25 10:41 UTC, mBeym commented on Services/User/templates/default/tpl.usr_field_change_listener_confirm.html
> +<ul>
Looks better/cleaner in my option than what $DIC->ui()->listing()-> does.
And easier as $DIC->ui()->listing()-> needs to be tricked into allowing nesting.

2021-10-25 11:46 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilMailAppEventListener.php
> +        if($this->isRelevantEvent()
Please apply the `PHP-CS-FIXER` on all changes files

2021-10-25 11:47 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilMailAppEventListener.php
> +            switch ((int) ($this->dic->settings()->get("mail_address_option") ?? 3)) {
Can we use a constant instead of `3` (there must be one already available)?

2021-10-25 11:48 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilMailAppEventListener.php
> +                    $this->dic->database()->manipulate(
Can we move the database manipulations to another/new class?

2021-10-25 12:01 UTC, mBeym commented on Services/Mail/classes/class.ilMailAppEventListener.php
> +                    $this->dic->database()->manipulate(
What's the benefit?

2021-10-25 12:02 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilMailAppEventListener.php
> +                    $this->dic->database()->manipulate(
Separation of concerns, single-responsibility principle, ... :-)`

2021-10-25 12:17 UTC, mjansenDatabay commented on Services/Mail/classes/Helper/class.ilMailDBHelper.php
> +class ilMailDBHelper
Please don't use the term `Helper` :-).

Please rename this class according to the actual domain event/use case, e.g. `ilMailGlobalAddressSettingsChangedCommand` (with dependencies injection) and add a `execute` method, where you execute both SQL statements.

2021-10-25 12:36 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilMailGlobalAddressSettingsChangedCommand.php
> +        global $DIC;
Please remove the `global $DIC;` and only pass the database instance instead.

2021-10-25 12:36 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilMailGlobalAddressSettingsChangedCommand.php
> +        $this->db->manipulate(
Please use `manipulateF` with type and value arrays.

2021-10-25 12:37 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilMailGlobalAddressSettingsChangedCommand.php
> +    public function execute(int $option) : void
Please pass the value to the constructor, execute should not have any parameters.

2021-10-25 12:37 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilMailAppEventListener.php
> +    public function __construct(ilMailGlobalAddressSettingsChangedCommand $globalAddressSettingsChangedCommand)
With `dependency` I meant: The `ilDBInterface` instance should be injected into `ilMailGlobalAddressSettingsChangedCommand`, not `ilMailGlobalAddressSettingsChangedCommand` into `ilMailAppEventListener` :-).

2021-10-25 13:08 UTC, mjansenDatabay commented on lang/ilias_en.lang
> +common#:#usr_field_change_components_listening#:#Components are listening for changes on a user field
```suggestion
common#:#There is at least one component which is interested in the changed configuration. Would you like to confirm the changes with the consequences the component(s) announced below?
```

2021-10-25 13:09 UTC, mjansenDatabay commented on lang/ilias_de.lang
> +common#:#usr_field_change_components_listening#:#Komponenten hören auf Änderrungen eines Benutzerfeldes
```suggestion
common#:#usr_field_change_components_listening#:#Es gibt mindestens eine Komponente, die sich für die getätigten Änderungen interessiert. Möchten Sie die Änderungen samt der von den Komponenten beschriebenen Konsequenzen final durchführen?
```

2021-10-25 13:33 UTC, mjansenDatabay commented on lang/ilias_de.lang
> +mail#:#usrFieldChange_second_mail_visible_in_personal_data#:#Lieber Administrator, im Feld "%" haben Sie das Attribut "%s" verändert.<br>Dies hat zur Folge, dass die bei den Benutzern gewählte E-Mail
```suggestion
mail#:#usrFieldChange_second_mail_visible_in_personal_data#:#Sie haben das Attribut "%s" im Feld "%s" verändert.<br>Dies führt dazu, dass, für alle bestehenden und künftig angelegten Konten, die bei den Benutzern gewählte Empfangsart und der Standard für neue Benutzerkonten bei externer Zustellung auf die primäre E-Mail-Adresse geändert wird, unter Inkaufnahme der Rücksetzung von bestehenden Benutzer-Einstellungen.
```

2021-10-25 13:33 UTC, mjansenDatabay commented on lang/ilias_en.lang
> +mail#:#usrFieldChange_second_mail_visible_in_personal_data#:#Dear administrator, in the field "%s" you have changed the attribute "%s".<br>This has the effect of changing the email address selected f
```suggestion
mail#:#usrFieldChange_second_mail_visible_in_personal_data#:#You have changed the attribute "%s" of the field "%s".<br>This leads to all accounts settings being reset to "receive on primary address" for external delivery, not only for all new accounts but also dismissing the currently active settings made by users.

2021-10-25 13:34 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilMailUserFieldChangeListener.php
> +                $fieldName, $attribute
```suggestion
                $attribute, $fieldName
```

2021-10-26 09:16 UTC, mjansenDatabay commented on Services/User/classes/class.ilObjUserFolderGUI.php
> +     * @return array<string, array{old: string, new: string}  Array containing all changed fields structured like this:
```suggestion
     * @return array<string, array{old: string, new: string}> Array containing all changed fields structured like this:
```

2021-10-26 09:16 UTC, mjansenDatabay commented on Services/User/classes/class.ilObjUserFolderGUI.php
> +     * @return array<string, array{old: string, new: string}  Array containing all changed fields structured like this:
@mBeym Maybe we shoul an class/interface here as well?

2021-10-26 09:17 UTC, mjansenDatabay commented on Services/User/classes/class.ilObjUserFolderGUI.php
> +     * @param array<string, array{old: string, new: string} $changedFields => See $this->collectChangedFields()
```suggestion
     * @param array<string, array{old: string, new: string}> $changedFields => See $this->collectChangedFields()
```

2021-10-26 09:17 UTC, mjansenDatabay commented on Services/User/classes/class.ilObjUserFolderGUI.php
> +     * @param array<string, array{old: string, new: string} $changedFields => See $this->collectChangedFields()
@mBeym Maybe we should introduce a class/interface here as well.

2021-10-26 10:39 UTC, mjansenDatabay commented on Services/User/classes/class.ilUserChangedField.php
> +}
Please apply the `PSR-CS-FIXER` to all changed files.

2021-10-26 10:39 UTC, mjansenDatabay commented on Services/User/classes/class.ilUserChangedField.php
> +class ilUserChangedField
```suggestion
class ChangedUserFieldAttribute
```

2021-10-26 10:41 UTC, mjansenDatabay commented on Services/User/interfaces/class.ilUserFieldChangeListener.php
> +abstract class ilUserFieldChangeListener
```suggestion
abstract class UserFieldAttributesChangeListener
```

2021-10-26 10:42 UTC, mjansenDatabay commented on Services/User/classes/class.ilInterestedUserFieldComponent.php
> +class ilInterestedUserFieldComponent
```suggestion
class InterestedUserFieldComponent
```

2021-10-26 19:52 UTC, mjansenDatabay requested changes
Please ...

- [x] ... use the `PHP-CS-FIXER` with the configuration file provided by ILIAS to apply the PSR-2 + X coding style standard.
- [x] ... add at least one unit test in `Services/User/test`
- [x] ... again squash all commits

Afterwards I'll cherry-pick your changes to `trunk`.

2024-08-23 11:23 UTC, closed without merging